// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop2City.DataLayer.Context;

#nullable disable

namespace Shop2City.DataLayer.Migrations
{
    [DbContext(typeof(Shop2CityContext))]
    [Migration("20240113071109_dfdsfsfdgdfgd")]
    partial class dfdsfsfdgdfgd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Calculations.CalculationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchasePrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.CalculationDetailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSelectedCalculationId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductSelectedCalculationId");

                    b.ToTable("CalculationDetails");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.DisCount", b =>
                {
                    b.Property<int>("disCountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("disCountId"));

                    b.Property<string>("disCountCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("disCountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("useableCount")
                        .HasColumnType("int");

                    b.HasKey("disCountId");

                    b.ToTable("DisCounts");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.Factor", b =>
                {
                    b.Property<int>("FactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactorId"));

                    b.Property<int>("FactorSum")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isFinaly")
                        .HasColumnType("bit");

                    b.Property<int>("totalPrice")
                        .HasColumnType("int");

                    b.Property<int>("typePostId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("FactorId");

                    b.HasIndex("typePostId");

                    b.HasIndex("userId");

                    b.ToTable("Factors", "Orders");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.FactorDetail", b =>
                {
                    b.Property<int>("FactorDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactorDetailId"));

                    b.Property<int>("FactorId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FactorDetailId");

                    b.HasIndex("FactorId");

                    b.HasIndex("ProductId");

                    b.ToTable("FactorDetails", "Orders");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.OrderDetailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinaly")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "Orders");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.TypePost", b =>
                {
                    b.Property<int>("TypePostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypePostId"));

                    b.Property<string>("TypePostTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("pricePost")
                        .HasColumnType("int");

                    b.HasKey("TypePostId");

                    b.ToTable("TypePosts");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Permissions.Permission", b =>
                {
                    b.Property<int>("permissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("permissionId"));

                    b.Property<string>("PermissionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("parentId")
                        .HasColumnType("int");

                    b.HasKey("permissionId");

                    b.HasIndex("parentId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Permissions.RolePermission", b =>
                {
                    b.Property<int>("rolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rolePermissionId"));

                    b.Property<int>("permissionId")
                        .HasColumnType("int");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.HasKey("rolePermissionId");

                    b.HasIndex("permissionId");

                    b.HasIndex("roleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.CategorySelectedCalculationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculationId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId");

                    b.ToTable("CategorySelectedCalculations");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("fullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("productCategory")
                        .HasColumnType("int");

                    b.Property<int>("productGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("productIsDelete")
                        .HasColumnType("bit");

                    b.Property<int?>("productSubCategory")
                        .HasColumnType("int");

                    b.Property<DateTime>("registerDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("shortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.HasIndex("productCategory");

                    b.HasIndex("productGroupId");

                    b.HasIndex("productSubCategory");

                    b.HasIndex("userId");

                    b.ToTable("Products", "Production");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.ProductGallery", b =>
                {
                    b.Property<int>("ProductGalleryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductGalleryId"));

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("ProductGalleryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductGalleries", "Production");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.ProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("parentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("parentId");

                    b.ToTable("ProductGroups");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.UserProduct", b =>
                {
                    b.Property<int>("userProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userProductId"));

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("userProductId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.ProductProperty", b =>
                {
                    b.Property<int>("PropertyProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyProductId"));

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("PropertyProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PropertyId");

                    b.ToTable("ProductProperties");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.Property", b =>
                {
                    b.Property<int>("propertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("propertyId"));

                    b.Property<int>("PropertyTitleId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("propertyId");

                    b.HasIndex("PropertyTitleId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.PropertyTechnical", b =>
                {
                    b.Property<int>("propertyTechnicalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("propertyTechnicalId"));

                    b.Property<string>("propertyTechnicalTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("propertyTechnicalId");

                    b.ToTable("propertyTechnicals");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.PropertyTechnicalProduct", b =>
                {
                    b.Property<int>("propertyTechnicalProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("propertyTechnicalProductId"));

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("propertyTechnicalId")
                        .HasColumnType("int");

                    b.Property<string>("propertyTechnicalProductValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("propertyTechnicalProductId");

                    b.HasIndex("productId");

                    b.HasIndex("propertyTechnicalId");

                    b.ToTable("PropertyTechnicalProducts");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.PropertyTitle", b =>
                {
                    b.Property<int>("PropertyTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyTitleId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyTitleId");

                    b.ToTable("PropertyTitles");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Settings.Setting", b =>
                {
                    b.Property<int>("settingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("settingId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cellPhone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("copyRight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logoImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("onlyShowConfirmedComment")
                        .HasColumnType("bit");

                    b.Property<string>("siteDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siteFavIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siteKeyWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siteTitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siteTitleFa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telPhone1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("settingId");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.ShoppingCartItems.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartItemId"));

                    b.Property<string>("CookieId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisterDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Session")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.ShoppingCarts.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.ShoppingCarts.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.ShoppingCarts.ShoppingCart", b =>
                {
                    b.Property<int>("shoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shoppingCartId"));

                    b.Property<string>("cookieId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<DateTime>("registerDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("shoppingCartgroupId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("shoppingCartId");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Slideshows.SlideShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndShowDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartShowDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SlideShows");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Sms", b =>
                {
                    b.Property<int>("SmsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SmsId"));

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("registerDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SmsId");

                    b.ToTable("Sms");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.LoginHistory", b =>
                {
                    b.Property<int>("LoginHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginHistoryId"));

                    b.Property<string>("CookieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleId"));

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<string>("roleTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("roleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.UserDiscountCode", b =>
                {
                    b.Property<int>("userDiscountCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userDiscountCodeId"));

                    b.Property<int>("disCountId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("userDiscountCodeId");

                    b.HasIndex("disCountId");

                    b.HasIndex("userId");

                    b.ToTable("UserDiscountCodes");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.UserLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LevelPercent")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserLevels");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.UserRole", b =>
                {
                    b.Property<int>("userRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userRoleId"));

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("userRoleId");

                    b.HasIndex("roleId");

                    b.HasIndex("userId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.CalculationDetailModel", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Orders.OrderModel", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Products.CategorySelectedCalculationModel", "ProductSelectedCalculation")
                        .WithMany()
                        .HasForeignKey("ProductSelectedCalculationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductSelectedCalculation");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.Factor", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Orders.TypePost", "TypePost")
                        .WithMany("Orders")
                        .HasForeignKey("typePostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Users.User", "User")
                        .WithMany("Factors")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypePost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.FactorDetail", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Orders.Factor", "Factor")
                        .WithMany("FactorDetails")
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Products.Product", "Product")
                        .WithMany("factorDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factor");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.OrderDetailModel", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Orders.OrderModel", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.OrderModel", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.ProductGroup", "OrderCategory")
                        .WithMany("OrderCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Products.ProductGroup", "OrderSubCategory")
                        .WithMany("OrderSubCategory")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Users.User", "User")
                        .WithMany("OrderModels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderCategory");

                    b.Navigation("OrderSubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Permissions.Permission", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Permissions.Permission", null)
                        .WithMany("permissions")
                        .HasForeignKey("parentId");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Permissions.RolePermission", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Permissions.Permission", "permission")
                        .WithMany("rolePermissions")
                        .HasForeignKey("permissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Users.Role", "role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.CategorySelectedCalculationModel", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Calculations.CalculationModel", "Calculation")
                        .WithMany("ProductSelectedCalculationModels")
                        .HasForeignKey("CalculationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.Product", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.ProductGroup", "Category")
                        .WithMany("Category")
                        .HasForeignKey("productCategory");

                    b.HasOne("Shop2City.DataLayer.Entities.Products.ProductGroup", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("productGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Products.ProductGroup", "SubCategory")
                        .WithMany("SubCategory")
                        .HasForeignKey("productSubCategory");

                    b.HasOne("Shop2City.DataLayer.Entities.Users.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ProductGroup");

                    b.Navigation("SubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.ProductGallery", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.Product", "Product")
                        .WithMany("ProductGalleries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.ProductGroup", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.ProductGroup", null)
                        .WithMany("ProductGroups")
                        .HasForeignKey("parentId");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.UserProduct", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.ProductProperty", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.Product", "Product")
                        .WithMany("ProductProperties")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Properties.Property", "Property")
                        .WithMany("ProductProperties")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.Property", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Properties.PropertyTitle", "PropertyTitle")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PropertyTitle");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.PropertyTechnicalProduct", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.Product", "Product")
                        .WithMany("PropertyTechnicalProducts")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Properties.PropertyTechnical", "PropertyTechnical")
                        .WithMany("PropertyTechnicalProducts")
                        .HasForeignKey("propertyTechnicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PropertyTechnical");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.ShoppingCartItems.ShoppingCartItem", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.ShoppingCarts.Item", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.ShoppingCarts.ShoppingCart", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Products.Product", "Product")
                        .WithMany("ShoppingCart")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Users.User", "User")
                        .WithMany("ShoppingCart")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.LoginHistory", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Users.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.UserDiscountCode", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Orders.DisCount", "DisCount")
                        .WithMany("UserDiscountCodes")
                        .HasForeignKey("disCountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DisCount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.UserRole", b =>
                {
                    b.HasOne("Shop2City.DataLayer.Entities.Users.Role", "role")
                        .WithMany("userRoles")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shop2City.DataLayer.Entities.Users.User", "user")
                        .WithMany("UserRoles")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Calculations.CalculationModel", b =>
                {
                    b.Navigation("ProductSelectedCalculationModels");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.DisCount", b =>
                {
                    b.Navigation("UserDiscountCodes");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.Factor", b =>
                {
                    b.Navigation("FactorDetails");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.OrderModel", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Orders.TypePost", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Permissions.Permission", b =>
                {
                    b.Navigation("permissions");

                    b.Navigation("rolePermissions");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.Product", b =>
                {
                    b.Navigation("ProductGalleries");

                    b.Navigation("ProductProperties");

                    b.Navigation("PropertyTechnicalProducts");

                    b.Navigation("ShoppingCart");

                    b.Navigation("factorDetails");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Products.ProductGroup", b =>
                {
                    b.Navigation("Category");

                    b.Navigation("OrderCategory");

                    b.Navigation("OrderSubCategory");

                    b.Navigation("ProductGroups");

                    b.Navigation("Products");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.Property", b =>
                {
                    b.Navigation("ProductProperties");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.PropertyTechnical", b =>
                {
                    b.Navigation("PropertyTechnicalProducts");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Properties.PropertyTitle", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.Role", b =>
                {
                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("Shop2City.DataLayer.Entities.Users.User", b =>
                {
                    b.Navigation("Factors");

                    b.Navigation("LoginHistories");

                    b.Navigation("OrderModels");

                    b.Navigation("Products");

                    b.Navigation("ShoppingCart");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
